dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: BJqhzA56/sPhWe2+NtZ5WtUp+siLDSpB5UYlY9zeL8XlLF8MWrA95k7bmXQKVG0kZ/Pt/ey4oryEAvE9kSPJF63g484p4rcwxGfZSPh0fc+EGV+jmCdY5sUj5QmFZHaozdoAJnHVzIaHAsAN80szTzFGr6IGHt6X76ogqJTseGmROcbuYKOTv0BgC7jAUVighXp4bRCjKW2QkHSAhj6/XqwPQjK9scp/mLSvDkNjJQnA7U6KvxfxDGLhtj0qEiMBSYssFhcT3cUTeVAT8144Aoz1wyW75zfhKYf7CUrwZ3DXA1j46R1ZZ5d559QJxezLnHWkAolxxryOREh6KdCnE7W5ewg3G+cbXck6+Vlg1zP0fCc/AE3fUZHmhaYSWEOZUT6ZMcFl3VgLBtmXipF/l40mVFCtqbAN32HU2pnmdnz7BgU7mFwqlU5JjCBjHFVpfEDJ9YolBBkBMIBZemp5rZ1eLN+Oc0zufa1q5drhapNcZfkjMRjl7+Yps2gIqq2jhlBNhTbvg6YgPviLj2YXtgetc8hnAPGepwppOHuVsz2MJVPR12YhVos46tDNET7SrPTqNqsCRcrbhSRtab1GzNmWzSJsmLqN10XcJB5Vz0rD+467XkMn7PldGy7eNIMb0Klmmj7xvH1HJRyQ/mP1Kp56ty7dDVT8bLF/QQD9WYg=
