- name: MongoDB provisioning
  hosts: all
  become: true
  tasks:
    - name: Add APT key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present

    - name: Add APT repository
      apt_repository:
        repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
        state: present

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Enable mongod service
      systemd:
        name: mongod
        enabled: yes
